### ISSUE TITLE
Respawn bug

### ISSUE THREAD

**Issue by andris155** [CookieSoftware/Tesseract#10]
#### Problem description

Respawn bug

#### Steps to reproduce the issue

https://youtu.be/KH1r9eJWa2c

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.19
* Server OS: Ubuntu
* Game version: 1.1.0.55
* Server host: VGH.hu
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by andris155** [comment]
Thanks!

**Comment by armagadon159753** [comment]
Now can you test it
I make me sure  its solved.

**Comment by andris155** [comment]
Wait for fix https://github.com/CookieSoftware/Tesseract/issues/14 and test.

**Comment by Crypt97** [comment]
It's still wrong!

**Comment by andris155** [comment]
I tested and not work.
