### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Crypt97** [CookieSoftware/Tesseract#11]
#### Problem description
[Tesseract] [12:56:09] [CRITICAL]: ClassNotFoundException: "Class pocketmine\network\mcpe\protocol\DataPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Tesseract] [12:56:09] [EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

#### Steps to reproduce the issue
1. start server

#### OS and versions
* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.17
* Server OS: Windows 10 Home
* Game version: 1.1.0.55
* Server host: local
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MasterOfTheRealm** [comment]
Problem Is Fixed Now.

**Comment by RateekMCPE** [comment]
Download the latest version. (Build)
