### ISSUE TITLE
[SOLVED] Some Sounds not work

### ISSUE THREAD

**Issue by BexiPE** [CookieSoftware/Tesseract#17]
ERROR:

$level = $player->getLevel();
$level->addSound(new PopSound($player));

[Tesseract] [08:28:34] [CRITICAL]: Error: "Undefined class constant 'EVENT_SOUND_POP'" (EXCEPTION) in "/src/pocketmine/level/sound/PopSound" at line 29

**Comment by CookieCode** [comment]
Explain, You have a screen of this error ?

**Comment by BexiPE** [comment]
Ehm I have writet it down.

**Comment by wiligangster** [comment]
Fixed https://github.com/CookieSoftware/Tesseract/commit/9eecb5b8a6364771494141c5db642edd10e86fd2

**Comment by RateekMCPE** [comment]
Without knowing your Tesseract version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
