### ISSUE TITLE
XD Funny bug (head)

### ISSUE THREAD

**Issue by Crypt97** [CookieSoftware/Tesseract#18]
#### Problem description
video: https://youtu.be/dBU1vjxdK2I

#### Steps to reproduce the issue
watch video: https://youtu.be/dBU1vjxdK2I

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.17
* Server OS: Windows 10 Home
* Game version: 1.1.0.55
* Server host: local
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MasterOfTheRealm** [comment]
Simple fix for that.

**Comment by MasterOfTheRealm** [comment]
Fixed.
