### ISSUE TITLE
#10 Respawn bug 

### ISSUE THREAD

**Issue by Crypt97** [CookieSoftware/Tesseract#19]
#10

**Comment by RateekMCPE** [comment]
Without knowing your Tesseract version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
