### ISSUE TITLE
Lag Bug!

### ISSUE THREAD

**Issue by BexiPE** [CookieSoftware/Tesseract#20]
sleep(2);
$player->getInventory()->setItem(1, $feast);
sleep(1);
$player->getInventory()->setItem(8, $back);

If I used this, it is lagging, and when I then move I bugging back.

[Tesseract] [10:12:15] [WARNING]: Bexiii moved too fast, reverting movement

**Comment by wiligangster** [comment]
Fixed ;)

**Comment by BexiPE** [comment]
Thanks (:

**Comment by BexiPE** [comment]
hm I have testet it but the Same bug.

**Comment by BexiPE** [comment]
Video of the bug.

https://youtu.be/kOxtsLUta-M

**Comment by wiligangster** [comment]
Please use the last src

**Comment by BexiPE** [comment]
Link?

**Comment by wiligangster** [comment]
Download zip

**Comment by BexiPE** [comment]
same bug.

**Comment by wiligangster** [comment]
Fixed again xD

**Comment by BexiPE** [comment]
same bug xD

**Comment by wiligangster** [comment]
WTF

**Comment by BexiPE** [comment]
I think that too xD

**Comment by BexiPE** [comment]
Will it fixed?

**Comment by MasterOfTheRealm** [comment]
Try enabling movement cheats

**Comment by BexiPE** [comment]
Hm I dont know where is it but I think it also not work because I'm lag and I cant writing.

**Comment by BexiPE** [comment]
Whit the old Tesseract it was working no Lag :/

**Comment by wiligangster** [comment]
Idk it's not my software fork. Use (Hydracon) doesnt lagg

**Comment by BexiPE** [comment]
What is that

**Comment by wiligangster** [comment]
https://github.com/E-DevPM/Hydracon

**Comment by BexiPE** [comment]
I have testet it same bug -.- :c

**Comment by wiligangster** [comment]
I test it work fine for me;
 what plugin you use ?

**Comment by BexiPE** [comment]
I use my Plugin (Lobby Items).

**Comment by MasterOfTheRealm** [comment]
@BexiPE it's in pocketmine.yml

**Comment by andris155** [comment]
Use timings and optimize your server!

**Comment by BexiPE** [comment]
Hm i dont know what you realy mean whit Timings. (My Server is a Localhost).

**Comment by eru12** [comment]
I can't ride ladder

**Comment by BexiPE** [comment]
@MasterOfTheRealm I cant find Cheats in it.

**Comment by BexiPE** [comment]
And what I do now :c?
Will it fix or not possible?

**Comment by MasterOfTheRealm** [comment]
It'll be fixed one way or another

**Comment by RateekMCPE** [comment]
Without knowing your Tesseract version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by BexiPE** [comment]
wow
