### ISSUE TITLE
Vine bug

### ISSUE THREAD

**Issue by Crypt97** [CookieSoftware/Tesseract#24]
#### Problem description
Notice: Undefined offset: 0 in C:\Users\pc\Desktop\Szervermcpe\src\pocketmine\block\Vine.php on line 157

#### Steps to reproduce the issue
i dont know

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.17
* Server OS: Windows 10 Home
* Game version: 1.1.0.55
* Server host: local
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by CookieCode** [comment]
Fixed : https://github.com/CookieSoftware/Tesseract/commit/ec9468a5e59d016c836bf9f20ee69bbd6b1a73fb
