### ISSUE TITLE
Vine, ladder climb not work

### ISSUE THREAD

**Issue by andris155** [CookieSoftware/Tesseract#9]
#### Problem description

vine, ladder climb not work

#### Steps to reproduce the issue

Place vine or ladder and press button

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.17
* Server OS: Windows 10
* Game version: 1.1.0.55
* Server host: My PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Crypt97** [comment]
Yes not work!

**Comment by wiligangster** [comment]
Hmm wait i fix it ;)

**Comment by Crypt97** [comment]
Video: https://youtu.be/W6-QIaWLnbc

**Comment by CookieCode** [comment]
Fixed : https://github.com/CookieSoftware/Tesseract/commit/9509d85db299a2b5931bdcdc9cd7c057f92c2283
